// Whitelist of major Canadian post-secondary institutions
// Verification works by uploading a student card or enrolment letter for an admin to review
// Order: alphabetical by shortName
const UNIVERSITIES = [
  // ── Universities (alphabetical) ──
  { name: 'Acadia University', shortName: 'Acadia University' },
  { name: 'Algoma University', shortName: 'Algoma University' },
  { name: 'Athabasca University', shortName: 'Athabasca University' },
  { name: 'Bishop\'s University', shortName: "Bishop's University" },
  { name: 'Brandon University', shortName: 'Brandon University' },
  { name: 'Brock University', shortName: 'Brock University' },
  { name: 'Cape Breton University', shortName: 'Cape Breton University (CBU)' },
  { name: 'Capilano University', shortName: 'Capilano University' },
  { name: 'Carleton University', shortName: 'Carleton University' },
  { name: 'Concordia University', shortName: 'Concordia University' },
  { name: 'Dalhousie University', shortName: 'Dalhousie University (Dal)' },
  { name: 'Emily Carr University of Art and Design', shortName: 'Emily Carr University (ECUAD)' },
  { name: 'Kwantlen Polytechnic University', shortName: 'Kwantlen Polytechnic University (KPU)' },
  { name: 'Lakehead University', shortName: 'Lakehead University' },
  { name: 'Laurentian University', shortName: 'Laurentian University' },
  { name: 'MacEwan University', shortName: 'MacEwan University' },
  { name: 'McGill University', shortName: 'McGill University' },
  { name: 'McMaster University', shortName: 'McMaster University' },
  { name: 'Memorial University of Newfoundland', shortName: 'Memorial University (MUN)' },
  { name: 'Mount Allison University', shortName: 'Mount Allison University' },
  { name: 'Mount Royal University', shortName: 'Mount Royal University' },
  { name: 'Mount Saint Vincent University', shortName: 'Mount Saint Vincent University (MSVU)' },
  { name: 'OCAD University', shortName: 'OCAD University' },
  { name: 'Queen\'s University', shortName: "Queen's University" },
  { name: 'Royal Roads University', shortName: 'Royal Roads University' },
  { name: 'Saint Francis Xavier University', shortName: 'Saint Francis Xavier University (StFX)' },
  { name: 'Saint Mary\'s University', shortName: "Saint Mary's University (SMU)" },
  { name: 'Simon Fraser University', shortName: 'Simon Fraser University (SFU)' },
  { name: 'St. Thomas University', shortName: 'St. Thomas University' },
  { name: 'Thompson Rivers University', shortName: 'Thompson Rivers University (TRU)' },
  { name: 'Toronto Metropolitan University', shortName: 'Toronto Metropolitan University (TMU)' },
  { name: 'Trent University', shortName: 'Trent University' },
  { name: 'Université de Montréal', shortName: 'Université de Montréal (UdeM)' },
  { name: 'Université du Québec à Montréal', shortName: 'Université du Québec à Montréal (UQAM)' },
  { name: 'Université Laval', shortName: 'Université Laval' },
  { name: 'University of Alberta', shortName: 'University of Alberta (UAlberta)' },
  { name: 'University of British Columbia', shortName: 'University of British Columbia (UBC)' },
  { name: 'University of Calgary', shortName: 'University of Calgary (UCalgary)' },
  { name: 'University of Guelph', shortName: 'University of Guelph (UofG)' },
  { name: 'University of Lethbridge', shortName: 'University of Lethbridge (ULeth)' },
  { name: 'University of Manitoba', shortName: 'University of Manitoba (UManitoba)' },
  { name: 'University of New Brunswick', shortName: 'University of New Brunswick (UNB)' },
  { name: 'University of Northern British Columbia', shortName: 'University of Northern BC (UNBC)' },
  { name: 'University of Ottawa', shortName: 'University of Ottawa (uOttawa)' },
  { name: 'University of Prince Edward Island', shortName: 'University of Prince Edward Island (UPEI)' },
  { name: 'University of Regina', shortName: 'University of Regina' },
  { name: 'University of Saskatchewan', shortName: 'University of Saskatchewan (USask)' },
  { name: 'University of Toronto', shortName: 'University of Toronto (UofT)' },
  { name: 'University of Victoria', shortName: 'University of Victoria (UVic)' },
  { name: 'University of Waterloo', shortName: 'University of Waterloo (UW)' },
  { name: 'University of Windsor', shortName: 'University of Windsor' },
  { name: 'Vancouver Island University', shortName: 'Vancouver Island University (VIU)' },
  { name: 'Western University', shortName: 'Western University' },
  { name: 'Wilfrid Laurier University', shortName: 'Wilfrid Laurier University' },
  { name: 'York University', shortName: 'York University' },

  // ── Colleges & Polytechnics (alphabetical) ──
  { name: 'Algonquin College', shortName: 'Algonquin College' },
  { name: 'BCIT', shortName: 'British Columbia Institute of Technology (BCIT)' },
  { name: 'Bow Valley College', shortName: 'Bow Valley College' },
  { name: 'Cambrian College', shortName: 'Cambrian College' },
  { name: 'Camosun College', shortName: 'Camosun College' },
  { name: 'Centennial College', shortName: 'Centennial College' },
  { name: 'College of New Caledonia', shortName: 'College of New Caledonia (CNC)' },
  { name: 'Conestoga College', shortName: 'Conestoga College' },
  { name: 'Douglas College', shortName: 'Douglas College' },
  { name: 'Durham College', shortName: 'Durham College' },
  { name: 'Fanshawe College', shortName: 'Fanshawe College' },
  { name: 'George Brown College', shortName: 'George Brown College' },
  { name: 'Humber College', shortName: 'Humber College' },
  { name: 'Langara College', shortName: 'Langara College' },
  { name: 'LaSalle College Montreal', shortName: 'LaSalle College Montreal' },
  { name: 'Lethbridge College', shortName: 'Lethbridge College' },
  { name: 'Loyalist College', shortName: 'Loyalist College' },
  { name: 'Mohawk College', shortName: 'Mohawk College' },
  { name: 'NAIT', shortName: 'Northern Alberta Institute of Technology (NAIT)' },
  { name: 'Niagara College', shortName: 'Niagara College' },
  { name: 'Okanagan College', shortName: 'Okanagan College' },
  { name: 'Red River College Polytechnic', shortName: 'Red River College Polytechnic' },
  { name: 'SAIT', shortName: 'Southern Alberta Institute of Technology (SAIT)' },
  { name: 'Selkirk College', shortName: 'Selkirk College' },
  { name: 'Seneca College', shortName: 'Seneca College' },
  { name: 'Sheridan College', shortName: 'Sheridan College' },
  { name: 'St. Lawrence College', shortName: 'St. Lawrence College' },
  { name: 'Vancouver Community College', shortName: 'Vancouver Community College (VCC)' },
];

// Old shortName → new shortName (for the DB migration)
const SHORT_NAME_MIGRATION = {
  // Fixes spacing errors around parentheses
  'University of Toronto(UofT)': 'University of Toronto (UofT)',
  'University of British Columbia(UBC)': 'University of British Columbia (UBC)',
  // Bare abbreviation → full name
  'UofT': 'University of Toronto (UofT)',
  'UBC': 'University of British Columbia (UBC)',
  'McGill': 'McGill University',
  'UAlberta': 'University of Alberta (UAlberta)',
  'Waterloo': 'University of Waterloo (UW)',
  'UW': 'University of Waterloo (UW)',
  'Western': 'Western University',
  "Queen's": "Queen's University",
  'SFU': 'Simon Fraser University (SFU)',
  'UCalgary': 'University of Calgary (UCalgary)',
  'uOttawa': 'University of Ottawa (uOttawa)',
  'Ottawa': 'University of Ottawa (uOttawa)',
  'York': 'York University',
  'UVic': 'University of Victoria (UVic)',
  'Dal': 'Dalhousie University (Dal)',
  'UManitoba': 'University of Manitoba (UManitoba)',
  'McMaster': 'McMaster University',
  'Carleton': 'Carleton University',
  'TMU': 'Toronto Metropolitan University (TMU)',
  'Ryerson': 'Toronto Metropolitan University (TMU)',
  'USask': 'University of Saskatchewan (USask)',
  'BCIT': 'British Columbia Institute of Technology (BCIT)',
  'Seneca': 'Seneca College',
  'George Brown': 'George Brown College',
  'Humber': 'Humber College',
  'SAIT': 'Southern Alberta Institute of Technology (SAIT)',
  'Langara': 'Langara College',
  // name field (full name) → normalized to shortName
  'University of Toronto': 'University of Toronto (UofT)',
  'University of British Columbia': 'University of British Columbia (UBC)',
  'University of Alberta': 'University of Alberta (UAlberta)',
  'University of Waterloo': 'University of Waterloo (UW)',
  'Simon Fraser University': 'Simon Fraser University (SFU)',
  'University of Calgary': 'University of Calgary (UCalgary)',
  'University of Ottawa': 'University of Ottawa (uOttawa)',
  'University of Victoria': 'University of Victoria (UVic)',
  'Dalhousie University': 'Dalhousie University (Dal)',
  'University of Manitoba': 'University of Manitoba (UManitoba)',
};

module.exports = { UNIVERSITIES, SHORT_NAME_MIGRATION };
