// 캐나다 주요 Post-Secondary 기관 화이트리스트
// 도메인은 이메일 자동 학교 인식용. 도메인 없는 학교도 서류 인증으로 사용 가능.
// 정렬: 알파벳순 (shortName 기준)
const UNIVERSITIES = [
  // ── Universities (알파벳순) ──
  { name: 'Acadia University', shortName: 'Acadia University', domains: ['acadiau.ca'] },
  { name: 'Algoma University', shortName: 'Algoma University', domains: ['algomau.ca'] },
  { name: 'Athabasca University', shortName: 'Athabasca University', domains: ['athabascau.ca'] },
  { name: 'Bishop\'s University', shortName: "Bishop's University", domains: ['ubishops.ca'] },
  { name: 'Brandon University', shortName: 'Brandon University', domains: ['brandonu.ca'] },
  { name: 'Brock University', shortName: 'Brock University', domains: ['brocku.ca'] },
  { name: 'Cape Breton University', shortName: 'Cape Breton University (CBU)', domains: ['cbu.ca'] },
  { name: 'Capilano University', shortName: 'Capilano University', domains: ['capilanou.ca'] },
  { name: 'Carleton University', shortName: 'Carleton University', domains: ['carleton.ca', 'cmail.carleton.ca'] },
  { name: 'Concordia University', shortName: 'Concordia University', domains: ['concordia.ca', 'mail.concordia.ca'] },
  { name: 'Dalhousie University', shortName: 'Dalhousie University (Dal)', domains: ['dal.ca'] },
  { name: 'Emily Carr University of Art and Design', shortName: 'Emily Carr University (ECUAD)', domains: ['ecuad.ca'] },
  { name: 'Kwantlen Polytechnic University', shortName: 'Kwantlen Polytechnic University (KPU)', domains: ['kpu.ca'] },
  { name: 'Lakehead University', shortName: 'Lakehead University', domains: ['lakeheadu.ca'] },
  { name: 'Laurentian University', shortName: 'Laurentian University', domains: ['laurentian.ca'] },
  { name: 'MacEwan University', shortName: 'MacEwan University', domains: ['macewan.ca'] },
  { name: 'McGill University', shortName: 'McGill University', domains: ['mail.mcgill.ca', 'mcgill.ca'] },
  { name: 'McMaster University', shortName: 'McMaster University', domains: ['mcmaster.ca'] },
  { name: 'Memorial University of Newfoundland', shortName: 'Memorial University (MUN)', domains: ['mun.ca'] },
  { name: 'Mount Allison University', shortName: 'Mount Allison University', domains: ['mta.ca'] },
  { name: 'Mount Royal University', shortName: 'Mount Royal University', domains: ['mtroyal.ca'] },
  { name: 'Mount Saint Vincent University', shortName: 'Mount Saint Vincent University (MSVU)', domains: ['msvu.ca'] },
  { name: 'OCAD University', shortName: 'OCAD University', domains: ['ocadu.ca'] },
  { name: 'Queen\'s University', shortName: "Queen's University", domains: ['queensu.ca'] },
  { name: 'Royal Roads University', shortName: 'Royal Roads University', domains: ['royalroads.ca'] },
  { name: 'Saint Francis Xavier University', shortName: 'Saint Francis Xavier University (StFX)', domains: ['stfx.ca'] },
  { name: 'Saint Mary\'s University', shortName: "Saint Mary's University (SMU)", domains: ['smu.ca'] },
  { name: 'Simon Fraser University', shortName: 'Simon Fraser University (SFU)', domains: ['sfu.ca'] },
  { name: 'St. Thomas University', shortName: 'St. Thomas University', domains: ['stu.ca'] },
  { name: 'Thompson Rivers University', shortName: 'Thompson Rivers University (TRU)', domains: ['tru.ca'] },
  { name: 'Toronto Metropolitan University', shortName: 'Toronto Metropolitan University (TMU)', domains: ['torontomu.ca', 'ryerson.ca'] },
  { name: 'Trent University', shortName: 'Trent University', domains: ['trentu.ca'] },
  { name: 'Université de Montréal', shortName: 'Université de Montréal (UdeM)', domains: ['umontreal.ca'] },
  { name: 'Université du Québec à Montréal', shortName: 'Université du Québec à Montréal (UQAM)', domains: ['uqam.ca'] },
  { name: 'Université Laval', shortName: 'Université Laval', domains: ['ulaval.ca'] },
  { name: 'University of Alberta', shortName: 'University of Alberta (UAlberta)', domains: ['ualberta.ca'] },
  { name: 'University of British Columbia', shortName: 'University of British Columbia (UBC)', domains: ['student.ubc.ca', 'ubc.ca'] },
  { name: 'University of Calgary', shortName: 'University of Calgary (UCalgary)', domains: ['ucalgary.ca'] },
  { name: 'University of Guelph', shortName: 'University of Guelph (UofG)', domains: ['uoguelph.ca'] },
  { name: 'University of Lethbridge', shortName: 'University of Lethbridge (ULeth)', domains: ['uleth.ca'] },
  { name: 'University of Manitoba', shortName: 'University of Manitoba (UManitoba)', domains: ['umanitoba.ca'] },
  { name: 'University of New Brunswick', shortName: 'University of New Brunswick (UNB)', domains: ['unb.ca'] },
  { name: 'University of Northern British Columbia', shortName: 'University of Northern BC (UNBC)', domains: ['unbc.ca'] },
  { name: 'University of Ottawa', shortName: 'University of Ottawa (uOttawa)', domains: ['uottawa.ca'] },
  { name: 'University of Prince Edward Island', shortName: 'University of Prince Edward Island (UPEI)', domains: ['upei.ca'] },
  { name: 'University of Regina', shortName: 'University of Regina', domains: ['uregina.ca'] },
  { name: 'University of Saskatchewan', shortName: 'University of Saskatchewan (USask)', domains: ['usask.ca'] },
  { name: 'University of Toronto', shortName: 'University of Toronto (UofT)', domains: ['mail.utoronto.ca', 'utoronto.ca'] },
  { name: 'University of Victoria', shortName: 'University of Victoria (UVic)', domains: ['uvic.ca'] },
  { name: 'University of Waterloo', shortName: 'University of Waterloo (UW)', domains: ['uwaterloo.ca'] },
  { name: 'University of Windsor', shortName: 'University of Windsor', domains: ['uwindsor.ca'] },
  { name: 'Vancouver Island University', shortName: 'Vancouver Island University (VIU)', domains: ['viu.ca'] },
  { name: 'Western University', shortName: 'Western University', domains: ['uwo.ca'] },
  { name: 'Wilfrid Laurier University', shortName: 'Wilfrid Laurier University', domains: ['wlu.ca', 'mylaurier.ca'] },
  { name: 'York University', shortName: 'York University', domains: ['yorku.ca'] },

  // ── Colleges & Polytechnics (알파벳순) ──
  { name: 'Algonquin College', shortName: 'Algonquin College', domains: ['algonquincollege.com'] },
  { name: 'BCIT', shortName: 'British Columbia Institute of Technology (BCIT)', domains: ['bcit.ca', 'my.bcit.ca'] },
  { name: 'Bow Valley College', shortName: 'Bow Valley College', domains: ['bowvalleycollege.ca'] },
  { name: 'Cambrian College', shortName: 'Cambrian College', domains: ['cambriancollege.ca'] },
  { name: 'Camosun College', shortName: 'Camosun College', domains: ['camosun.ca'] },
  { name: 'Centennial College', shortName: 'Centennial College', domains: ['centennialcollege.ca', 'my.centennialcollege.ca'] },
  { name: 'College of New Caledonia', shortName: 'College of New Caledonia (CNC)', domains: ['cnc.bc.ca'] },
  { name: 'Conestoga College', shortName: 'Conestoga College', domains: ['conestogac.on.ca'] },
  { name: 'Douglas College', shortName: 'Douglas College', domains: ['douglascollege.ca'] },
  { name: 'Durham College', shortName: 'Durham College', domains: ['durhamcollege.ca'] },
  { name: 'Fanshawe College', shortName: 'Fanshawe College', domains: ['fanshawec.ca'] },
  { name: 'George Brown College', shortName: 'George Brown College', domains: ['georgebrown.ca'] },
  { name: 'Humber College', shortName: 'Humber College', domains: ['humber.ca', 'humberc.ca'] },
  { name: 'Langara College', shortName: 'Langara College', domains: ['langara.ca'] },
  { name: 'LaSalle College Montreal', shortName: 'LaSalle College Montreal', domains: ['collegelasalle.com'] },
  { name: 'Lethbridge College', shortName: 'Lethbridge College', domains: ['lethbridgecollege.ca'] },
  { name: 'Loyalist College', shortName: 'Loyalist College', domains: ['loyalistcollege.com'] },
  { name: 'Mohawk College', shortName: 'Mohawk College', domains: ['mohawkcollege.ca'] },
  { name: 'NAIT', shortName: 'Northern Alberta Institute of Technology (NAIT)', domains: ['nait.ca'] },
  { name: 'Niagara College', shortName: 'Niagara College', domains: ['niagaracollege.ca'] },
  { name: 'Okanagan College', shortName: 'Okanagan College', domains: ['okanagan.bc.ca'] },
  { name: 'Red River College Polytechnic', shortName: 'Red River College Polytechnic', domains: ['rrc.ca'] },
  { name: 'SAIT', shortName: 'Southern Alberta Institute of Technology (SAIT)', domains: ['sait.ca', 'my.sait.ca'] },
  { name: 'Selkirk College', shortName: 'Selkirk College', domains: ['selkirk.ca'] },
  { name: 'Seneca College', shortName: 'Seneca College', domains: ['myseneca.ca'] },
  { name: 'Sheridan College', shortName: 'Sheridan College', domains: ['sheridancollege.ca'] },
  { name: 'St. Lawrence College', shortName: 'St. Lawrence College', domains: ['sl.on.ca'] },
  { name: 'Vancouver Community College', shortName: 'Vancouver Community College (VCC)', domains: ['vcc.ca'] },
];

// 기존 shortName → 새 shortName 매핑 (DB 마이그레이션용)
const SHORT_NAME_MIGRATION = {
  // 괄호 공백 오류 수정
  'University of Toronto(UofT)': 'University of Toronto (UofT)',
  'University of British Columbia(UBC)': 'University of British Columbia (UBC)',
  // 단순 약어 → 풀네임
  'UofT': 'University of Toronto (UofT)',
  'UBC': 'University of British Columbia (UBC)',
  'McGill': 'McGill University',
  'UAlberta': 'University of Alberta (UAlberta)',
  'Waterloo': 'University of Waterloo (UW)',
  'UW': 'University of Waterloo (UW)',
  'Western': 'Western University',
  "Queen's": "Queen's University",
  'SFU': 'Simon Fraser University (SFU)',
  'UCalgary': 'University of Calgary (UCalgary)',
  'uOttawa': 'University of Ottawa (uOttawa)',
  'Ottawa': 'University of Ottawa (uOttawa)',
  'York': 'York University',
  'UVic': 'University of Victoria (UVic)',
  'Dal': 'Dalhousie University (Dal)',
  'UManitoba': 'University of Manitoba (UManitoba)',
  'McMaster': 'McMaster University',
  'Carleton': 'Carleton University',
  'TMU': 'Toronto Metropolitan University (TMU)',
  'Ryerson': 'Toronto Metropolitan University (TMU)',
  'USask': 'University of Saskatchewan (USask)',
  'BCIT': 'British Columbia Institute of Technology (BCIT)',
  'Seneca': 'Seneca College',
  'George Brown': 'George Brown College',
  'Humber': 'Humber College',
  'SAIT': 'Southern Alberta Institute of Technology (SAIT)',
  'Langara': 'Langara College',
  // name 필드(풀네임) → shortName 통일
  'University of Toronto': 'University of Toronto (UofT)',
  'University of British Columbia': 'University of British Columbia (UBC)',
  'University of Alberta': 'University of Alberta (UAlberta)',
  'University of Waterloo': 'University of Waterloo (UW)',
  'Simon Fraser University': 'Simon Fraser University (SFU)',
  'University of Calgary': 'University of Calgary (UCalgary)',
  'University of Ottawa': 'University of Ottawa (uOttawa)',
  'University of Victoria': 'University of Victoria (UVic)',
  'Dalhousie University': 'Dalhousie University (Dal)',
  'University of Manitoba': 'University of Manitoba (UManitoba)',
};

// 이메일 도메인으로 대학교 찾기
function findUniversityByEmail(email) {
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return null;
  return UNIVERSITIES.find(u => u.domains.includes(domain)) || null;
}

module.exports = { UNIVERSITIES, SHORT_NAME_MIGRATION, findUniversityByEmail };
